# Generated by Django 5.2.2 on 2025-06-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField(max_length=500)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('activo', models.BooleanField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
