# Generated by Django 5.2.2 on 2025-06-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='id_cliente',
            field=models.CharField(error_messages='El texto debe tener max 8 digitos', max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_registro',
            field=models.DateTimeField(),
        ),
    ]
