# Generated by Django 5.2.2 on 2025-07-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_cliente_id_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_registro', models.DateField()),
                ('id_Cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetallesVenta',
            fields=[
                ('id_DetalleVenta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.producto')),
                ('id_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.venta')),
            ],
        ),
    ]
