# Generated by Django 5.2.2 on 2025-07-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_venta_detallesventa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallesventa',
            old_name='id_DetalleVenta',
            new_name='id_detalleVenta',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='id_Cliente',
            new_name='id_cliente',
        ),
    ]
