# Generated by Django 5.2.2 on 2025-07-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0005_rename_id_detalleventa_detallesventa_id_detalleventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_detalleVenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venta.detallesventa'),
        ),
    ]
