# Generated by Django 5.2.2 on 2025-07-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_venta_id_detalleventa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_detalleVenta',
        ),
    ]
