# Generated by Django 5.2.2 on 2025-07-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_remove_venta_id_detalleventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesventa',
            name='id_detalleVenta',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_venta',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
